services:
  - type: web
    name: job-board-api
    env: docker
    dockerfilePath: Job-Board/Dockerfile
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/Job-Board-0.0.1-SNAPSHOT.jar
    rootDir: Job-Board
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQLHOST
        value: mysql.railway.internal
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: GIUthrIHTOzPmWibbNRHKHmdGkPAsrTf
      - key: MYSQLDATABASE
        value: job_board_app_db
      - key: MYSQLPORT
        value: 3306
