services:
  - type: web
    name: job-board-api
    env: docker
    dockerfilePath: Job-Board/Dockerfile
    rootDir: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQLHOST
        value: mysql.railway.internal
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: GIUthrIHTOzPmWibbNRHKHmdGkPAsrTf
      - key: MYSQLDATABASE
        value: job_board_app_db
      - key: MYSQLPORT
        value: 3306
