services:
  - type: web
    name: Job-Board
    runtime: java
    buildCommand: ./mvnw clean install
    startCommand: ./mvnw spring-boot:run
    envVars:
      - key: DATASOURCE_URL
        value: jdbc:mysql://127.0.0.1:3307/job_board_app_db?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      - key: DATASOURCE_USERNAME
        value: root
      - key: FRONTEND_URL
        value: http://localhost:3000
